-- CreateTable
CREATE TABLE "Discussion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "zooniverse_id" TEXT,
    "href" TEXT,
    "board_id" TEXT,
    "comments_count" INTEGER,
    "created_at" DATETIME,
    "focus_id" TEXT,
    "last_comment_created_at" DATETIME,
    "locked" BOOLEAN,
    "project_id" TEXT,
    "section" TEXT,
    "sticky" BOOLEAN,
    "subject_default" BOOLEAN,
    "title" TEXT,
    "updated_at" DATETIME,
    "user_id" TEXT,
    "user_login" TEXT,
    "users_count" INTEGER,
    "project_slug" TEXT,
    "project_title" TEXT,
    "board_comments_count" INTEGER,
    "board_description" TEXT,
    "board_discussions_count" INTEGER,
    "board_parent_id" TEXT,
    "board_subject_default" BOOLEAN,
    "board_title" TEXT,
    "board_users_count" INTEGER,
    "user_display_name" TEXT
);
